service: cookunity-meals

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  architecture: arm64
  stage: production
  region: us-west-2
  memorySize: 512
  logRetentionInDays: 1
  timeout: 15
  

functions:
  api:
    handler: dist/lambda.handler
    events:
      - httpApi:
          method: any
          path: /{proxy+}
    environment:
      JWT_KEY: "${env:JWT_KEY}"
      DB_HOST: "${env:DB_HOST}"
      DB_PORT: "${env:DB_PORT}"
      DB_USERNAME: "${env:DB_USERNAME}"
      DB_PASSWORD: "${env:DB_PASSWORD}"
      DB_DATABASE: "${env:DB_DATABASE}"

  queue:
    handler: dist/events-queue.handler
    events:
      - sqs:
          batchSize: 1
          arn:
            Fn::GetAtt:
              - MealsEventsReceiver
              - Arn
    environment:
      JWT_KEY: "${env:JWT_KEY}"
      DB_HOST: "${env:DB_HOST}"
      DB_PORT: "${env:DB_PORT}"
      DB_USERNAME: "${env:DB_USERNAME}"
      DB_PASSWORD: "${env:DB_PASSWORD}"
      DB_DATABASE: "${env:DB_DATABASE}"

resources:
  Resources:
    MealsEventsReceiver:
      Type: "AWS::SQS::Queue"
      Properties:
        QueueName: "MealsEventsReceiver"
    SnsMealsEventsReceiverAccessPolicy:
      Type: AWS::SQS::QueuePolicy
      Properties:
        PolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Sid: "allow-sns-messages"
              Effect: "Allow"
              Principal:
                Service:
                  - "sns.amazonaws.com"
              Resource: 
                Fn::GetAtt:
                  - MealsEventsReceiver
                  - Arn
              Action: "SQS:SendMessage"
              Condition:
                ArnEquals:
                  "aws:SourceArn": "arn:aws:sns:${aws:region}:${aws:accountId}:reviews"
        Queues:
          - Ref: MealsEventsReceiver
    MealsEventsReceiverSNSSubscription:
      Type: 'AWS::SNS::Subscription'
      Properties:
        TopicArn: "arn:aws:sns:${aws:region}:${aws:accountId}:reviews"
        Endpoint: !GetAtt
          - MealsEventsReceiver
          - Arn
        Protocol: sqs
        RawMessageDelivery: 'false'


plugins:
  - serverless-jetpack
  - serverless-offline